### PR TITLE
Add authentication support

### PR DESCRIPTION
**Pull request by trasher**
My Eco-Devices is protected with the password it provides (simple HTTP authentication).

I've never worked on a home assistant component before; but I've been able to make it work :)

### CODE REVIEW

**Comment by Aohzan** [comment]
Hello @trasher, thanks for the PR, I will try this week-end on my ecodevices

**Comment by Aohzan** [comment]
Tested and approved, I let you see my review, I will merge after that :)

**Comment by trasher** [comment]
> Tested and approved, 

Cool :)

> I let you see my review, I will merge after that :)

Hum... Your review? Maybe you forget to submit it?

**Review by Aohzan — CHANGES_REQUESTED** [review]

**Comment by Aohzan** [comment]
I will close this PR since I began a full rewrite with your modification: https://github.com/Aohzan/ecodevices/pull/4
You can contribute on it if you wants

**Pull request closed without merging**
